services:
  - type: web
    name: alina-mega-sales-aibot
    env: python
    build:
      pythonVersion: 3.10.13
      buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    branch: main
    repo: https://github.com/Alex1966design/alina-mega-sales-aibot